// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vmuyjqwpnqtvrlceqmwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdXlqcXdwbnF0dnJsY2VxbXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MDM1MDgsImV4cCI6MjA4Mzk3OTUwOH0.CYviQcLwoXVJkTPCw9cp1e0Oruu1qDhD2esK3N44Fcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
